//! **GENERATED by `cargo xtask gen-model-data` — do not edit by hand.**
//! Source: `models.snapshot.json`. Verified by `cargo xtask check-model-data`.

#![allow(rustdoc::broken_intra_doc_links)]

use crate::catalog::{ModelEntry, ThinkingFormat};
use crate::model_context::ModelContextEntry;
use crate::smart_router::RoutingTier;

/// The canonical snapshot JSON (structure-stable; see `models.manifest.json`).
pub static CATALOG_JSON: &str = r#"{
  "models": [
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 32000,
      "model_id": "claude-opus",
      "provider": "anthropic",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "interleaved",
      "tier": "Powerful"
    },
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 16000,
      "model_id": "claude-sonnet",
      "provider": "anthropic",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "interleaved",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 8192,
      "model_id": "claude-haiku",
      "provider": "anthropic",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "interleaved",
      "tier": "Cheap"
    },
    {
      "cache_retention": true,
      "context_window": 1000000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 32000,
      "model_id": "gpt-4.1-nano",
      "provider": "openai",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Cheap"
    },
    {
      "cache_retention": true,
      "context_window": 1000000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 32000,
      "model_id": "gpt-4.1-mini",
      "provider": "openai",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 1000000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 32000,
      "model_id": "gpt-4.1",
      "provider": "openai",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 128000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 16384,
      "model_id": "gpt-4o-mini",
      "provider": "openai",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Cheap"
    },
    {
      "cache_retention": true,
      "context_window": 128000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 16384,
      "model_id": "gpt-4o",
      "provider": "openai",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 100000,
      "model_id": "o4-mini",
      "provider": "openai",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Cheap"
    },
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 100000,
      "model_id": "o3-pro",
      "provider": "openai",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Powerful"
    },
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 100000,
      "model_id": "o3-mini",
      "provider": "openai",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 200000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 100000,
      "model_id": "o3",
      "provider": "openai",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 2000000,
      "input_modalities": [
        "text",
        "image",
        "audio",
        "video"
      ],
      "max_output_tokens": 8192,
      "model_id": "gemini-2.5-pro",
      "provider": "gemini",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Powerful"
    },
    {
      "cache_retention": true,
      "context_window": 1000000,
      "input_modalities": [
        "text",
        "image",
        "audio",
        "video"
      ],
      "max_output_tokens": 8192,
      "model_id": "gemini-2.5-flash",
      "provider": "gemini",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 1000000,
      "input_modalities": [
        "text",
        "image",
        "audio",
        "video"
      ],
      "max_output_tokens": 8192,
      "model_id": "gemini-2.0-flash",
      "provider": "gemini",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Cheap"
    },
    {
      "cache_retention": true,
      "context_window": 203000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 16384,
      "model_id": "glm-5",
      "provider": "glm",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "interleaved",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 128000,
      "input_modalities": [
        "text",
        "image"
      ],
      "max_output_tokens": 4096,
      "model_id": "glm-4",
      "provider": "glm",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": true,
      "context_window": 64000,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 32000,
      "model_id": "deepseek-reasoner",
      "provider": "deepseek",
      "reasoning": true,
      "supports_strict": false,
      "thinking_format": "separate",
      "tier": "Powerful"
    },
    {
      "cache_retention": true,
      "context_window": 128000,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 8192,
      "model_id": "deepseek-chat",
      "provider": "deepseek",
      "reasoning": false,
      "supports_strict": false,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": false,
      "context_window": 128000,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 8192,
      "model_id": "qwen3",
      "provider": "qwen",
      "reasoning": true,
      "supports_strict": true,
      "thinking_format": "separate",
      "tier": "Balanced"
    },
    {
      "cache_retention": false,
      "context_window": 128000,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 8192,
      "model_id": "qwen2.5",
      "provider": "qwen",
      "reasoning": false,
      "supports_strict": true,
      "thinking_format": "none",
      "tier": "Cheap"
    },
    {
      "cache_retention": false,
      "context_window": 128000,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 4096,
      "model_id": "llama3.3",
      "provider": "llama",
      "reasoning": false,
      "supports_strict": false,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": false,
      "context_window": 128000,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 4096,
      "model_id": "llama3.1",
      "provider": "llama",
      "reasoning": false,
      "supports_strict": false,
      "thinking_format": "none",
      "tier": "Balanced"
    },
    {
      "cache_retention": false,
      "context_window": 8192,
      "input_modalities": [
        "text"
      ],
      "max_output_tokens": 4096,
      "model_id": "llama3",
      "provider": "llama",
      "reasoning": false,
      "supports_strict": false,
      "thinking_format": "none",
      "tier": "Cheap"
    }
  ],
  "schema_version": 1
}
"#;

/// The generated model catalog — L3 authority.
pub static CATALOG: &[ModelEntry] = &[
    ModelEntry {
        provider: "anthropic",
        model_id: "claude-opus",
        context_window: 200000,
        max_output_tokens: 32000,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Interleaved,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Powerful,
    },
    ModelEntry {
        provider: "anthropic",
        model_id: "claude-sonnet",
        context_window: 200000,
        max_output_tokens: 16000,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Interleaved,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "anthropic",
        model_id: "claude-haiku",
        context_window: 200000,
        max_output_tokens: 8192,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Interleaved,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Cheap,
    },
    ModelEntry {
        provider: "openai",
        model_id: "gpt-4.1-nano",
        context_window: 1000000,
        max_output_tokens: 32000,
        reasoning: false,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Cheap,
    },
    ModelEntry {
        provider: "openai",
        model_id: "gpt-4.1-mini",
        context_window: 1000000,
        max_output_tokens: 32000,
        reasoning: false,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "openai",
        model_id: "gpt-4.1",
        context_window: 1000000,
        max_output_tokens: 32000,
        reasoning: false,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "openai",
        model_id: "gpt-4o-mini",
        context_window: 128000,
        max_output_tokens: 16384,
        reasoning: false,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Cheap,
    },
    ModelEntry {
        provider: "openai",
        model_id: "gpt-4o",
        context_window: 128000,
        max_output_tokens: 16384,
        reasoning: false,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "openai",
        model_id: "o4-mini",
        context_window: 200000,
        max_output_tokens: 100000,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Cheap,
    },
    ModelEntry {
        provider: "openai",
        model_id: "o3-pro",
        context_window: 200000,
        max_output_tokens: 100000,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Powerful,
    },
    ModelEntry {
        provider: "openai",
        model_id: "o3-mini",
        context_window: 200000,
        max_output_tokens: 100000,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "openai",
        model_id: "o3",
        context_window: 200000,
        max_output_tokens: 100000,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "gemini",
        model_id: "gemini-2.5-pro",
        context_window: 2000000,
        max_output_tokens: 8192,
        reasoning: true,
        input_modalities: &["text", "image", "audio", "video"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Powerful,
    },
    ModelEntry {
        provider: "gemini",
        model_id: "gemini-2.5-flash",
        context_window: 1000000,
        max_output_tokens: 8192,
        reasoning: true,
        input_modalities: &["text", "image", "audio", "video"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "gemini",
        model_id: "gemini-2.0-flash",
        context_window: 1000000,
        max_output_tokens: 8192,
        reasoning: false,
        input_modalities: &["text", "image", "audio", "video"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Cheap,
    },
    ModelEntry {
        provider: "glm",
        model_id: "glm-5",
        context_window: 203000,
        max_output_tokens: 16384,
        reasoning: true,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::Interleaved,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "glm",
        model_id: "glm-4",
        context_window: 128000,
        max_output_tokens: 4096,
        reasoning: false,
        input_modalities: &["text", "image"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "deepseek",
        model_id: "deepseek-reasoner",
        context_window: 64000,
        max_output_tokens: 32000,
        reasoning: true,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: false,
        cache_retention: true,
        tier: RoutingTier::Powerful,
    },
    ModelEntry {
        provider: "deepseek",
        model_id: "deepseek-chat",
        context_window: 128000,
        max_output_tokens: 8192,
        reasoning: false,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::None,
        supports_strict: false,
        cache_retention: true,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "qwen",
        model_id: "qwen3",
        context_window: 128000,
        max_output_tokens: 8192,
        reasoning: true,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::Separate,
        supports_strict: true,
        cache_retention: false,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "qwen",
        model_id: "qwen2.5",
        context_window: 128000,
        max_output_tokens: 8192,
        reasoning: false,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::None,
        supports_strict: true,
        cache_retention: false,
        tier: RoutingTier::Cheap,
    },
    ModelEntry {
        provider: "llama",
        model_id: "llama3.3",
        context_window: 128000,
        max_output_tokens: 4096,
        reasoning: false,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::None,
        supports_strict: false,
        cache_retention: false,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "llama",
        model_id: "llama3.1",
        context_window: 128000,
        max_output_tokens: 4096,
        reasoning: false,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::None,
        supports_strict: false,
        cache_retention: false,
        tier: RoutingTier::Balanced,
    },
    ModelEntry {
        provider: "llama",
        model_id: "llama3",
        context_window: 8192,
        max_output_tokens: 4096,
        reasoning: false,
        input_modalities: &["text"],
        thinking_format: ThinkingFormat::None,
        supports_strict: false,
        cache_retention: false,
        tier: RoutingTier::Cheap,
    },
];

/// Context-window projection — stable L3 record kept for API compatibility.
/// Generated from `CATALOG` so the two never drift.
pub static BUILTIN_MODEL_CONTEXT: &[ModelContextEntry] = &[
    ModelContextEntry {
        provider: "anthropic",
        model_id: "claude-opus",
        context_window: 200000,
        max_output_tokens: 32000,
    },
    ModelContextEntry {
        provider: "anthropic",
        model_id: "claude-sonnet",
        context_window: 200000,
        max_output_tokens: 16000,
    },
    ModelContextEntry {
        provider: "anthropic",
        model_id: "claude-haiku",
        context_window: 200000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "gpt-4.1-nano",
        context_window: 1000000,
        max_output_tokens: 32000,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "gpt-4.1-mini",
        context_window: 1000000,
        max_output_tokens: 32000,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "gpt-4.1",
        context_window: 1000000,
        max_output_tokens: 32000,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "gpt-4o-mini",
        context_window: 128000,
        max_output_tokens: 16384,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "gpt-4o",
        context_window: 128000,
        max_output_tokens: 16384,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "o4-mini",
        context_window: 200000,
        max_output_tokens: 100000,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "o3-pro",
        context_window: 200000,
        max_output_tokens: 100000,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "o3-mini",
        context_window: 200000,
        max_output_tokens: 100000,
    },
    ModelContextEntry {
        provider: "openai",
        model_id: "o3",
        context_window: 200000,
        max_output_tokens: 100000,
    },
    ModelContextEntry {
        provider: "gemini",
        model_id: "gemini-2.5-pro",
        context_window: 2000000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "gemini",
        model_id: "gemini-2.5-flash",
        context_window: 1000000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "gemini",
        model_id: "gemini-2.0-flash",
        context_window: 1000000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "glm",
        model_id: "glm-5",
        context_window: 203000,
        max_output_tokens: 16384,
    },
    ModelContextEntry {
        provider: "glm",
        model_id: "glm-4",
        context_window: 128000,
        max_output_tokens: 4096,
    },
    ModelContextEntry {
        provider: "deepseek",
        model_id: "deepseek-reasoner",
        context_window: 64000,
        max_output_tokens: 32000,
    },
    ModelContextEntry {
        provider: "deepseek",
        model_id: "deepseek-chat",
        context_window: 128000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "qwen",
        model_id: "qwen3",
        context_window: 128000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "qwen",
        model_id: "qwen2.5",
        context_window: 128000,
        max_output_tokens: 8192,
    },
    ModelContextEntry {
        provider: "llama",
        model_id: "llama3.3",
        context_window: 128000,
        max_output_tokens: 4096,
    },
    ModelContextEntry {
        provider: "llama",
        model_id: "llama3.1",
        context_window: 128000,
        max_output_tokens: 4096,
    },
    ModelContextEntry {
        provider: "llama",
        model_id: "llama3",
        context_window: 8192,
        max_output_tokens: 4096,
    },
];
