// scenario-editor.js — the cross-frontend scenario editor (VS Code webview +
// browser popup). Single source of truth; committed copies live at
//   platforms/vscode/src/webview/scenario-editor.js
//   platforms/browser/scenario-editor.js
// (regenerated by `platforms/shared/sync.sh`). DO NOT edit the copies.
//
// Edits a BusScenario (name + cast + turn policy) — the rich scenario store
// unit surfaced by `scenario/*`. Live-validates on every edit via
// `scenario/validate` (the single authoritative validator — no per-frontend
// mirror to drift), saves via `scenario/upsert`, deletes via `scenario/delete`.
// Transport-agnostic: takes a `rpc` exposing `call(method, params) → result`
// (the VS Code postMessage client + the browser native-messaging client both
// expose this surface), plus a root DOM element to mount into.

(function (global) {
  "use strict";

  /** A fresh blank BusScenario (matches the engine `BusScenario` shape; the
   *  store assigns a stable id on first upsert). */
  function blankScenario() {
    var t = Date.now();
    return {
      id: "sc-" + t,
      name: "",
      members: [{ id: "m" + t, name: "", system_prompt: "", kind: "openai", model: "" }],
      turn_policy: "roundrobin",
    };
  }

  /**
   * @param {object} opts
   * @param {object} opts.rpc           — { call(method, params) → Promise<result> }
   * @param {HTMLElement} opts.root     — mount point
   * @param {(id: string)=>void} [opts.onSaved]   — after a successful upsert
   * @param {(id: string)=>void} [opts.onDeleted] — after a delete
   * @param {(msg: string)=>void} [opts.onError]  — transport/error surfacing
   * @returns {{render: Function, edit: Function, newScenario: Function}}
   */
  function create(opts) {
    var rpc = opts.rpc;
    var root = opts.root;
    var onSaved = opts.onSaved || function () {};
    var onDeleted = opts.onDeleted || function () {};
    var onError = opts.onError || function () {};

    var editing = null; // the BusScenario being edited
    var validateTimer = null;

    /** Load the first preset (or a blank) as the editing target. */
    async function pickFirstPreset() {
      try {
        var res = await rpc.call("scenario/list", {});
        editing = ((res && res.scenarios) || [])[0] || blankScenario();
      } catch (e) {
        editing = blankScenario();
      }
    }

    /** Edit a specific scenario (e.g. clicked in the sidebar). */
    function edit(sc) {
      editing = sc ? JSON.parse(JSON.stringify(sc)) : blankScenario();
      render();
    }

    function newScenario() {
      editing = blankScenario();
      render();
    }

    /** (Re)draw the editor form. Picks a preset if no scenario is loaded. */
    async function render() {
      if (!editing) await pickFirstPreset();
      root.innerHTML = "";

      // ── Name ──
      var name = field("Name", "input", editing.name);
      name.input.addEventListener("input", function () {
        editing.name = name.input.value;
        scheduleValidate();
      });
      root.appendChild(name.row);

      // ── Turn policy ──
      var policy = field("Turn policy", "select", editing.turn_policy,
        ["scripted", "moderator", "roundrobin"]);
      policy.input.addEventListener("change", function () {
        editing.turn_policy = policy.input.value;
        scheduleValidate();
      });
      root.appendChild(policy.row);

      // ── Cast ──
      var castHeader = document.createElement("div");
      castHeader.textContent = "Cast";
      castHeader.style.fontWeight = "bold";
      root.appendChild(castHeader);
      (editing.members || []).forEach(function (m, i) {
        root.appendChild(memberRow(m, i));
      });

      var addMember = document.createElement("button");
      addMember.textContent = "+ member";
      addMember.addEventListener("click", function () {
        editing.members.push({ id: "m" + Date.now(), name: "", system_prompt: "", kind: "openai", model: "" });
        render();
      });
      root.appendChild(addMember);

      // ── Actions ──
      var actions = document.createElement("div");
      actions.style.marginTop = "8px";
      var save = document.createElement("button");
      save.textContent = "Save";
      save.addEventListener("click", saveScenario);
      var del = document.createElement("button");
      del.textContent = "Delete";
      del.style.marginLeft = "6px";
      del.addEventListener("click", deleteScenario);
      var fresh = document.createElement("button");
      fresh.textContent = "New";
      fresh.style.marginLeft = "6px";
      fresh.addEventListener("click", newScenario);
      actions.appendChild(save);
      actions.appendChild(del);
      actions.appendChild(fresh);
      root.appendChild(actions);

      // ── Validation errors ──
      var errBox = document.createElement("div");
      errBox.className = "errors";
      errBox.id = "scenario-errors";
      root.appendChild(errBox);

      scheduleValidate();
    }

    function memberRow(m, i) {
      var row = document.createElement("div");
      row.className = "field";
      row.style.border = "1px solid #eee";
      var nm = document.createElement("input");
      nm.value = m.name;
      nm.placeholder = "name";
      nm.addEventListener("input", function () {
        m.name = nm.value;
        scheduleValidate();
      });
      var prompt = document.createElement("input");
      prompt.value = m.system_prompt;
      prompt.placeholder = "system prompt";
      prompt.addEventListener("input", function () {
        m.system_prompt = prompt.value;
        scheduleValidate();
      });
      var wrap = document.createElement("div");
      wrap.className = "row";
      wrap.appendChild(nm);
      wrap.appendChild(prompt);
      row.appendChild(wrap);
      var remove = document.createElement("button");
      remove.textContent = "remove";
      remove.addEventListener("click", function () {
        editing.members.splice(i, 1);
        render();
      });
      row.appendChild(remove);
      return row;
    }

    /** Debounced live validate — avoids a round-trip per keystroke. */
    function scheduleValidate() {
      if (validateTimer) clearTimeout(validateTimer);
      validateTimer = setTimeout(validate, 200);
    }

    async function validate() {
      if (!editing) return;
      var box = document.getElementById("scenario-errors");
      if (!box) return;
      var res;
      try {
        res = await rpc.call("scenario/validate", { scenario: editing });
      } catch (e) {
        box.innerHTML = "";
        box.textContent = "validate unavailable: " + e.message;
        return;
      }
      var errs = (res && res.errors) || [];
      box.innerHTML = "";
      for (var i = 0; i < errs.length; i++) {
        var d = document.createElement("div");
        d.textContent = errs[i].field + ": " + errs[i].message;
        box.appendChild(d);
      }
    }

    async function saveScenario() {
      try {
        var res = await rpc.call("scenario/upsert", { scenario: editing });
        if (res && res.ok === false) return; // errors already shown by validate()
        onSaved(editing.id);
      } catch (e) {
        onError("save failed: " + e.message);
      }
    }

    async function deleteScenario() {
      if (!editing) return;
      try {
        await rpc.call("scenario/delete", { id: editing.id });
        onDeleted(editing.id);
        await pickFirstPreset();
        render();
      } catch (e) {
        onError("delete failed: " + e.message);
      }
    }

    function field(label, tag, value, options) {
      var row = document.createElement("div");
      row.className = "field";
      var lab = document.createElement("label");
      lab.textContent = label;
      var input =
        tag === "select"
          ? document.createElement("select")
          : document.createElement(tag === "textarea" ? "textarea" : "input");
      if (tag === "select") {
        for (var i = 0; i < options.length; i++) {
          var opt = document.createElement("option");
          opt.value = options[i];
          opt.textContent = options[i];
          if (options[i] === value) opt.selected = true;
          input.appendChild(opt);
        }
      } else {
        input.value = value || "";
      }
      row.appendChild(lab);
      row.appendChild(input);
      return { row: row, input: input };
    }

    return { render: render, edit: edit, newScenario: newScenario };
  }

  global.OneAiScenarioEditor = { create: create, blankScenario: blankScenario };
})(typeof window !== "undefined" ? window : this);
