#!/usr/bin/env bash
# install-host.sh — register the OneAI native-messaging host so Chrome/Firefox
# can spawn `oneai app-server --listen native-messaging` on
# `chrome.runtime.connectNative('com.oneai.appserver')`. Zero manual server
# start: the browser owns the spawn (Codex model for the browser case).
#
# The host manifest points at a wrapper script that execs the `oneai` binary
# with `--listen native-messaging` (Chrome launches the manifest `path` with
# no args, so a wrapper is required). The 4-byte LE length-prefix framing the
# browser speaks matches `serve_native_messaging` (Phase A).
#
# Usage:
#   ./install-host.sh --browser=chrome --ext-id=<your-extension-id>
#   ./install-host.sh --browser=firefox --ext-id=oneai@oneai
#
# Get the extension id: load the unpacked extension at chrome://extensions
# (dev mode), copy the id; or for a signed .crx it's derived from the key.
set -euo pipefail

HOST_NAME="com.oneai.appserver"
ONEAI_BIN="${ONEAI_BIN:-oneai}"
BROWSER="chrome"
EXT_ID=""

for arg in "$@"; do
  case "$arg" in
    --browser=*) BROWSER="${arg#*=}" ;;
    --ext-id=*) EXT_ID="${arg#*=}" ;;
    --bin=*) ONEAI_BIN="${arg#*=}" ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ "$BROWSER" != "chrome" && "$BROWSER" != "firefox" ]]; then
  echo "browser must be chrome or firefox" >&2; exit 2
fi
if [[ -z "$EXT_ID" ]]; then
  echo "ERROR: pass --ext-id=<id> (the loaded extension's id at chrome://extensions)" >&2
  exit 2
fi

# Resolve the oneai binary to an absolute path (the manifest `path` must be
# absolute). `command -v` searches PATH.
ONEAI_PATH="$(command -v "$ONEAI_BIN" || true)"
if [[ -z "$ONEAI_PATH" ]]; then
  echo "ERROR: '$ONEAI_BIN' not found on PATH. Install oneai or pass --bin=/path/to/oneai" >&2
  exit 1
fi
ONEAI_PATH="$(cd "$(dirname "$ONEAI_PATH")" && pwd)/$(basename "$ONEAI_PATH")"
echo "oneai binary: $ONEAI_PATH"

mkdir -p "$HOME/.oneai"
WRAPPER="$HOME/.oneai/oneai-nm-host.sh"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by OneAI install-host.sh — Chrome launches this with no args; it
# execs the engine in native-messaging host mode. stdout is the message stream
# (4B-LE framed); do not print anything else here.
exec "$ONEAI_PATH" app-server --listen native-messaging
EOF
chmod +x "$WRAPPER"
echo "wrapper: $WRAPPER"

# Build the manifest JSON. Chrome uses allowed_origins (extension ids);
# Firefox uses allowed_extensions.
MANIFEST_JSON=$(cat <<EOF
{
  "name": "$HOST_NAME",
  "description": "OneAI engine native-messaging host",
  "path": "$WRAPPER",
  "type": "stdio",
  $(if [[ "$BROWSER" == "chrome" ]]; then
    echo "\"allowed_origins\": [\"chrome-extension://$EXT_ID/\"]"
  else
    echo "\"allowed_extensions\": [\"$EXT_ID\"]"
  fi)
}
EOF
)

case "$BROWSER" in
  chrome)
    # macOS + Linux Chrome host dirs. The script picks the one for this OS.
    if [[ -d "$HOME/Library/Application Support/Google/Chrome" ]]; then
      DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
    elif [[ -d "$HOME/.config/google-chrome" ]]; then
      DIR="$HOME/.config/google-chrome/NativeMessagingHosts"
    elif [[ -d "$HOME/.config/chromium" ]]; then
      DIR="$HOME/.config/chromium/NativeMessagingHosts"
    else
      echo "ERROR: no Chrome config dir found (looked in the standard macOS/Linux locations)" >&2
      exit 1
    fi
    ;;
  firefox)
    if [[ -d "$HOME/Library/Application Support/Mozilla" ]]; then
      DIR="$HOME/Library/Application Support/Mozilla/NativeMessagingHosts"
    else
      DIR="$HOME/.mozilla/native-messaging-hosts"
    fi
    ;;
esac

mkdir -p "$DIR"
OUT="$DIR/$HOST_NAME.json"
echo "$MANIFEST_JSON" > "$OUT"
echo "manifest: $OUT"
echo
echo "Done. Reload the extension at chrome://extensions, then open the OneAI popup."
echo "Troubleshoot: chrome://native-internals shows connect/disconnect reasons."
