//! A2A Protocol data types — complete type definitions per the Google A2A specification.
//!
//! The A2A (Agent-to-Agent) protocol defines a standardized way for AI agents
//! to discover each other's capabilities and collaborate on tasks. This module
//! implements all the core data types from the specification:
//!
//! - **AgentCard**: Discovery metadata describing an agent's capabilities
//! - **Task**: The central unit of work in A2A, with a lifecycle of states
//! - **Message**: Communication turns between client and agent
//! - **Part**: Polymorphic content (text, files, structured data)
//! - **Artifact**: Outputs generated by the agent during task execution
//!
//! All types implement `serde::Serialize` and `serde::Deserialize` for
//! JSON-RPC message transport, following the A2A specification's naming
//! conventions (camelCase for JSON, kebab-case for enum values).

use serde::{Deserialize, Serialize};

// ─── TaskState ─────────────────────────────────────────────────────────────────

/// Task lifecycle state — tracks the progression of an A2A Task.
///
/// The state machine defines these valid transitions:
/// - `Submitted` → `Working`
/// - `Working` → `Completed` | `Failed` | `InputRequired` | `Canceled`
/// - `InputRequired` → `Working`
/// - Any state → terminal (`Completed`, `Failed`, `Canceled`, `Rejected`)
///
/// Use `validate_transition()` to check if a state change is valid.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "kebab-case")]
pub enum TaskState {
    /// Task has been created/submitted but not yet started.
    Submitted,
    /// Agent is actively processing the task.
    Working,
    /// Agent needs additional input from the client to continue.
    InputRequired,
    /// Task has finished successfully with a result.
    Completed,
    /// Task was canceled (by client or agent).
    Canceled,
    /// Task encountered an error and could not complete.
    Failed,
    /// Agent rejected the task before starting work.
    Rejected,
}

impl std::fmt::Display for TaskState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TaskState::Submitted => write!(f, "submitted"),
            TaskState::Working => write!(f, "working"),
            TaskState::InputRequired => write!(f, "input-required"),
            TaskState::Completed => write!(f, "completed"),
            TaskState::Canceled => write!(f, "canceled"),
            TaskState::Failed => write!(f, "failed"),
            TaskState::Rejected => write!(f, "rejected"),
        }
    }
}

impl TaskState {
    /// Check whether this state is terminal (no further transitions possible).
    pub fn is_terminal(&self) -> bool {
        matches!(self, TaskState::Completed | TaskState::Failed | TaskState::Canceled | TaskState::Rejected)
    }

    /// Validate that a transition from `from` to `to` is allowed by the A2A spec.
    pub fn validate_transition(from: &TaskState, to: &TaskState) -> bool {
        match from {
            TaskState::Submitted => matches!(to, TaskState::Working | TaskState::Rejected | TaskState::Canceled),
            TaskState::Working => matches!(to, TaskState::Completed | TaskState::Failed | TaskState::InputRequired | TaskState::Canceled),
            TaskState::InputRequired => matches!(to, TaskState::Working | TaskState::Canceled | TaskState::Failed),
            // Terminal states — no further transitions allowed
            TaskState::Completed | TaskState::Failed | TaskState::Canceled | TaskState::Rejected => false,
        }
    }
}

// ─── Part (discriminated union) ────────────────────────────────────────────────

/// Polymorphic content part — the fundamental content unit in A2A messages and artifacts.
///
/// A Part can be:
/// - **Text**: Plain text content
/// - **File**: Binary/file content via URI or inline base64 bytes
/// - **Data**: Structured/arbitrary JSON data
///
/// Uses serde's internally tagged representation with `"type"` as the discriminant,
/// matching the A2A specification's `oneOf` schema pattern.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum Part {
    /// Plain text content.
    Text {
        /// The text content.
        text: String,
    },
    /// File content — either a URI reference or inline base64 bytes.
    File {
        /// The file content descriptor.
        file: FileContent,
    },
    /// Structured/arbitrary key-value data payload.
    Data {
        /// The structured data (any JSON object).
        data: serde_json::Value,
    },
}

// ─── FileContent ───────────────────────────────────────────────────────────────

/// File content descriptor — provides either a URI reference or inline base64 bytes.
///
/// At least one of `uri` or `bytes` must be provided per the A2A spec.
/// The `mime_type` field is optional and describes the file's content type.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FileContent {
    /// URI reference to the file (optional — alternative to inline bytes).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// Inline base64-encoded file bytes (optional — alternative to URI).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
    /// MIME type of the file (e.g., "image/png", "application/pdf").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
}

impl FileContent {
    /// Create a FileContent with a URI reference.
    pub fn from_uri(uri: String, mime_type: Option<String>) -> Self {
        Self { uri: Some(uri), bytes: None, mime_type }
    }

    /// Create a FileContent with inline base64 bytes.
    pub fn from_bytes(bytes: String, mime_type: Option<String>) -> Self {
        Self { uri: None, bytes: Some(bytes), mime_type }
    }
}

// ─── Message ───────────────────────────────────────────────────────────────────

/// A communication turn between the client and the agent during a task.
///
/// Each message has a `role` (who sent it) and a list of `Part` objects
/// (the content). Messages are the building blocks of task history.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Message {
    /// Who sent the message — `"user"` (client) or `"agent"` (remote agent).
    pub role: MessageRole,
    /// Content parts — polymorphic content units (text, files, data).
    pub parts: Vec<Part>,
    /// Optional extension metadata (key-value pairs).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

/// Message role — identifies who sent the message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MessageRole {
    /// Message from the client (user).
    #[serde(rename = "user")]
    User,
    /// Message from the remote agent.
    #[serde(rename = "agent")]
    Agent,
}

impl Message {
    /// Create a simple user text message.
    pub fn user_text(text: impl Into<String>) -> Self {
        Self {
            role: MessageRole::User,
            parts: vec![Part::Text { text: text.into() }],
            metadata: None,
        }
    }

    /// Create a simple agent text message.
    pub fn agent_text(text: impl Into<String>) -> Self {
        Self {
            role: MessageRole::Agent,
            parts: vec![Part::Text { text: text.into() }],
            metadata: None,
        }
    }
}

// ─── TaskStatus ────────────────────────────────────────────────────────────────

/// Task status — the current state of a task, with optional context message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TaskStatus {
    /// The current lifecycle state.
    pub state: TaskState,
    /// Optional message providing context about the state change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<Message>,
    /// ISO 8601 timestamp of the state update.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl TaskStatus {
    /// Create a new TaskStatus with just a state.
    pub fn new(state: TaskState) -> Self {
        Self { state, message: None, timestamp: None }
    }

    /// Create a TaskStatus with state and context message.
    pub fn with_message(state: TaskState, message: Message) -> Self {
        Self { state, message: Some(message), timestamp: None }
    }
}

// ─── Task ───────────────────────────────────────────────────────────────────────

/// Task — the central unit of work in A2A.
///
/// A Task represents an ongoing or completed interaction between a client
/// agent and a remote agent. It tracks the lifecycle state, conversation
/// history, and any outputs (artifacts) produced.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Task {
    /// Unique task identifier (UUID).
    pub id: String,
    /// Optional session identifier to group related tasks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Current task status (state + optional message + timestamp).
    pub status: TaskStatus,
    /// Conversation history — messages exchanged during the task.
    /// Only available when the remote agent supports `stateTransitionHistory`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub history: Vec<Message>,
    /// Outputs generated by the agent during task execution.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub artifacts: Vec<Artifact>,
    /// Optional extension metadata (key-value pairs).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl Task {
    /// Create a new Task with the given ID and initial submitted state.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            session_id: None,
            status: TaskStatus::new(TaskState::Submitted),
            history: Vec::new(),
            artifacts: Vec::new(),
            metadata: None,
        }
    }

    /// Check whether the task is in a terminal state.
    pub fn is_terminal(&self) -> bool {
        self.status.state.is_terminal()
    }

    /// Attempt a state transition. Returns Ok(new_state) if valid, Err if invalid.
    pub fn transition_to(&mut self, new_state: TaskState) -> Result<TaskState, crate::error::A2AError> {
        if !TaskState::validate_transition(&self.status.state, &new_state) {
            return Err(crate::error::A2AError::InvalidStateTransition {
                from: self.status.state.clone(),
                to: new_state,
            });
        }
        self.status.state = new_state.clone();
        Ok(new_state)
    }

    /// Add an artifact to the task.
    pub fn add_artifact(&mut self, artifact: Artifact) {
        self.artifacts.push(artifact);
    }

    /// Add a message to the task history.
    pub fn add_message(&mut self, message: Message) {
        self.history.push(message);
    }
}

// ─── Artifact ───────────────────────────────────────────────────────────────────

/// Artifact — a generated output/product from a task.
///
/// Artifacts are distinct from intermediate messages — they represent the
/// final outputs of the task (e.g., generated files, reports, data).
///
/// For streaming, artifacts use `index`, `append`, and `lastChunk` fields
/// to represent incremental chunks of a larger output.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Artifact {
    /// Position index in a streaming sequence (0-based).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub index: Option<usize>,
    /// Whether this artifact chunk appends to the previous one (streaming).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub append: Option<bool>,
    /// Whether this is the final chunk of the artifact (streaming).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_chunk: Option<bool>,
    /// Content parts — the same polymorphic Part types as Messages.
    #[serde(default)]
    pub parts: Vec<Part>,
    /// Optional human-readable name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Optional extension metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl Artifact {
    /// Create a simple text artifact.
    pub fn text(name: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            index: None,
            append: None,
            last_chunk: None,
            parts: vec![Part::Text { text: text.into() }],
            name: Some(name.into()),
            description: None,
            metadata: None,
        }
    }

    /// Create a streaming artifact chunk.
    pub fn streaming_chunk(index: usize, parts: Vec<Part>, append: bool, last_chunk: bool) -> Self {
        Self {
            index: Some(index),
            append: Some(append),
            last_chunk: Some(last_chunk),
            parts,
            name: None,
            description: None,
            metadata: None,
        }
    }
}

// ─── AgentSkill ─────────────────────────────────────────────────────────────────

/// AgentSkill — describes an individual skill/capability that an agent offers.
///
/// Skills are the primary way for agents to advertise what they can do.
/// Each skill has a unique ID, name, description, and examples of how
/// to invoke it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AgentSkill {
    /// Unique identifier for the skill.
    pub id: String,
    /// Human-readable name of the skill.
    pub name: String,
    /// Detailed description of what the skill does.
    pub description: String,
    /// Categorization tags for the skill.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// Example prompts/queries that invoke this skill.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub examples: Vec<String>,
    /// Supported input content types for this specific skill.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub input_modes: Vec<String>,
    /// Supported output content types for this specific skill.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub output_modes: Vec<String>,
}

impl AgentSkill {
    /// Create a simple skill with ID, name, and description.
    pub fn new(id: impl Into<String>, name: impl Into<String>, description: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            description: description.into(),
            tags: Vec::new(),
            examples: Vec::new(),
            input_modes: vec!["text/plain".to_string()],
            output_modes: vec!["text/plain".to_string()],
        }
    }
}

// ─── AgentCapabilities ──────────────────────────────────────────────────────────

/// Agent capabilities — feature flags describing what the agent supports.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AgentCapabilities {
    /// Whether the agent supports SSE streaming for task updates.
    #[serde(default)]
    pub streaming: bool,
    /// Whether the agent supports push notifications for task updates.
    #[serde(default)]
    pub push_notifications: bool,
    /// Whether the agent provides state transition history in task responses.
    #[serde(default)]
    pub state_transition_history: bool,
}

// ─── AuthenticationInfo ─────────────────────────────────────────────────────────

/// Authentication information — describes security requirements for accessing the agent.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct AuthenticationInfo {
    /// Supported authentication schemes (e.g., ["bearer", "basic"]).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub schemes: Vec<String>,
    /// Optional credentials or token description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credentials: Option<String>,
}

// ─── AgentCard ──────────────────────────────────────────────────────────────────

/// AgentCard — the discovery/profile document that an agent publishes.
///
/// The AgentCard is the core metadata document in A2A. It describes:
/// - Who the agent is (name, description, provider)
/// - What it can do (skills)
/// - How to reach it (url)
/// - What features it supports (capabilities)
/// - How to authenticate (authentication)
///
/// A well-known endpoint (typically `/.well-known/agent-card`) serves
/// this document for agent discovery.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AgentCard {
    /// Human-readable name of the agent.
    pub name: String,
    /// Description of the agent's capabilities.
    pub description: String,
    /// The URL endpoint where the agent can be reached (A2A server).
    pub url: String,
    /// Version of the agent (e.g., "1.0.0").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Provider/organization info.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<AgentProvider>,
    /// Skills the agent offers.
    #[serde(default)]
    pub skills: Vec<AgentSkill>,
    /// Default content types for input.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub default_input_modes: Vec<String>,
    /// Default content types for output.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub default_output_modes: Vec<String>,
    /// Feature capabilities the agent supports.
    #[serde(default)]
    pub capabilities: AgentCapabilities,
    /// Authentication requirements.
    #[serde(default)]
    pub authentication: AuthenticationInfo,
    /// Optional URL to agent documentation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub documentation_url: Option<String>,
}

/// Provider/organization info for an agent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentProvider {
    /// Organization name.
    pub organization: String,
    /// Organization URL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AgentCard {
    /// Create a minimal AgentCard with name, description, and URL.
    pub fn new(name: impl Into<String>, description: impl Into<String>, url: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: description.into(),
            url: url.into(),
            version: None,
            provider: None,
            skills: Vec::new(),
            default_input_modes: vec!["text/plain".to_string()],
            default_output_modes: vec!["text/plain".to_string()],
            capabilities: AgentCapabilities::default(),
            authentication: AuthenticationInfo::default(),
            documentation_url: None,
        }
    }

    /// Parse an AgentCard from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, crate::error::A2AError> {
        serde_json::from_str(json).map_err(|e| crate::error::A2AError::Serialization(e.to_string()))
    }

    /// Serialize this AgentCard to a JSON string.
    pub fn to_json(&self) -> Result<String, crate::error::A2AError> {
        serde_json::to_string(self).map_err(|e| crate::error::A2AError::Serialization(e.to_string()))
    }

    /// Serialize this AgentCard to a pretty-printed JSON string.
    pub fn to_json_pretty(&self) -> Result<String, crate::error::A2AError> {
        serde_json::to_string_pretty(self).map_err(|e| crate::error::A2AError::Serialization(e.to_string()))
    }
}

// ─── PushNotificationConfig ──────────────────────────────────────────────────────

/// Push notification configuration — for receiving async updates on long-running tasks.
///
/// When a client needs asynchronous updates on a task (rather than polling),
/// it registers a callback URL where the agent will send push notifications
/// when the task status changes.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PushNotificationConfig {
    /// The callback endpoint URL where push notifications are sent.
    pub url: String,
    /// Authentication requirements for the notification endpoint.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub authentication: Option<AuthenticationInfo>,
}

// ─── SendTaskParams ─────────────────────────────────────────────────────────────

/// Parameters for the `tasks/send` JSON-RPC method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SendTaskParams {
    /// Unique task identifier. If new, creates a task; if existing, continues it.
    pub id: String,
    /// The message to send to the agent.
    pub message: Message,
    /// Optional session ID to group related tasks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Number of recent messages to return in the task's history.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history_length: Option<usize>,
    /// Push notification configuration for async updates.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub push_notification: Option<PushNotificationConfig>,
    /// Optional extension metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

// ─── GetTaskParams ──────────────────────────────────────────────────────────────

/// Parameters for the `tasks/get` JSON-RPC method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetTaskParams {
    /// The task identifier to retrieve.
    pub id: String,
    /// Number of recent messages to include in the history.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history_length: Option<usize>,
}

// ─── CancelTaskParams ───────────────────────────────────────────────────────────

/// Parameters for the `tasks/cancel` JSON-RPC method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CancelTaskParams {
    /// The task identifier to cancel.
    pub id: String,
}

// ─── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ─── TaskState transition tests ──────────────────────────────────────────────

    #[test]
    fn test_valid_transitions() {
        assert!(TaskState::validate_transition(&TaskState::Submitted, &TaskState::Working));
        assert!(TaskState::validate_transition(&TaskState::Submitted, &TaskState::Rejected));
        assert!(TaskState::validate_transition(&TaskState::Submitted, &TaskState::Canceled));
        assert!(TaskState::validate_transition(&TaskState::Working, &TaskState::Completed));
        assert!(TaskState::validate_transition(&TaskState::Working, &TaskState::Failed));
        assert!(TaskState::validate_transition(&TaskState::Working, &TaskState::InputRequired));
        assert!(TaskState::validate_transition(&TaskState::Working, &TaskState::Canceled));
        assert!(TaskState::validate_transition(&TaskState::InputRequired, &TaskState::Working));
        assert!(TaskState::validate_transition(&TaskState::InputRequired, &TaskState::Canceled));
        assert!(TaskState::validate_transition(&TaskState::InputRequired, &TaskState::Failed));
    }

    #[test]
    fn test_invalid_transitions() {
        // Can't go from submitted directly to terminal states (except rejected/canceled)
        assert!(!TaskState::validate_transition(&TaskState::Submitted, &TaskState::Completed));
        assert!(!TaskState::validate_transition(&TaskState::Submitted, &TaskState::Failed));
        assert!(!TaskState::validate_transition(&TaskState::Submitted, &TaskState::InputRequired));
        // Can't go from terminal states to any other state
        assert!(!TaskState::validate_transition(&TaskState::Completed, &TaskState::Working));
        assert!(!TaskState::validate_transition(&TaskState::Failed, &TaskState::Working));
        assert!(!TaskState::validate_transition(&TaskState::Canceled, &TaskState::Working));
        assert!(!TaskState::validate_transition(&TaskState::Rejected, &TaskState::Working));
        // Can't go from working back to submitted
        assert!(!TaskState::validate_transition(&TaskState::Working, &TaskState::Submitted));
    }

    #[test]
    fn test_terminal_states() {
        assert!(TaskState::Completed.is_terminal());
        assert!(TaskState::Failed.is_terminal());
        assert!(TaskState::Canceled.is_terminal());
        assert!(TaskState::Rejected.is_terminal());
        assert!(!TaskState::Submitted.is_terminal());
        assert!(!TaskState::Working.is_terminal());
        assert!(!TaskState::InputRequired.is_terminal());
    }

    // ─── Part serialization tests ────────────────────────────────────────────────

    #[test]
    fn test_text_part_serialization() {
        let part = Part::Text { text: "Hello, world!".to_string() };
        let json = serde_json::to_string(&part).unwrap();
        assert!(json.contains("\"type\":\"text\""));
        assert!(json.contains("\"text\":\"Hello, world!\""));

        let deserialized: Part = serde_json::from_str(&json).unwrap();
        assert_eq!(part, deserialized);
    }

    #[test]
    fn test_file_part_serialization() {
        let part = Part::File {
            file: FileContent::from_uri("https://example.com/file.pdf".to_string(), Some("application/pdf".to_string())),
        };
        let json = serde_json::to_string(&part).unwrap();
        assert!(json.contains("\"type\":\"file\""));
        assert!(json.contains("\"uri\":\"https://example.com/file.pdf\""));
        assert!(json.contains("\"mimeType\":\"application/pdf\""));

        let deserialized: Part = serde_json::from_str(&json).unwrap();
        assert_eq!(part, deserialized);
    }

    #[test]
    fn test_data_part_serialization() {
        let part = Part::Data {
            data: serde_json::json!({"key": "value", "count": 42}),
        };
        let json = serde_json::to_string(&part).unwrap();
        assert!(json.contains("\"type\":\"data\""));
        assert!(json.contains("\"data\""));

        let deserialized: Part = serde_json::from_str(&json).unwrap();
        assert_eq!(part, deserialized);
    }

    #[test]
    fn test_file_content_bytes() {
        let file = FileContent::from_bytes("base64data".to_string(), Some("image/png".to_string()));
        assert_eq!(file.uri, None);
        assert_eq!(file.bytes, Some("base64data".to_string()));
        assert_eq!(file.mime_type, Some("image/png".to_string()));
    }

    #[test]
    fn test_file_content_uri() {
        let file = FileContent::from_uri("https://example.com/doc.pdf".to_string(), None);
        assert_eq!(file.uri, Some("https://example.com/doc.pdf".to_string()));
        assert_eq!(file.bytes, None);
        assert_eq!(file.mime_type, None);
    }

    // ─── Message tests ───────────────────────────────────────────────────────────

    #[test]
    fn test_user_text_message() {
        let msg = Message::user_text("Analyze this code");
        assert_eq!(msg.role, MessageRole::User);
        assert_eq!(msg.parts.len(), 1);
        assert_eq!(msg.metadata, None);
    }

    #[test]
    fn test_agent_text_message() {
        let msg = Message::agent_text("Analysis complete");
        assert_eq!(msg.role, MessageRole::Agent);
        assert_eq!(msg.parts.len(), 1);
    }

    #[test]
    fn test_message_serialization_roundtrip() {
        let msg = Message {
            role: MessageRole::User,
            parts: vec![
                Part::Text { text: "Hello".to_string() },
                Part::Data { data: serde_json::json!({"query": "search"}) },
            ],
            metadata: Some(serde_json::json!({"source": "test"})),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let deserialized: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, deserialized);
    }

    // ─── TaskStatus tests ────────────────────────────────────────────────────────

    #[test]
    fn test_task_status_new() {
        let status = TaskStatus::new(TaskState::Working);
        assert_eq!(status.state, TaskState::Working);
        assert_eq!(status.message, None);
        assert_eq!(status.timestamp, None);
    }

    #[test]
    fn test_task_status_with_message() {
        let msg = Message::agent_text("Processing started");
        let status = TaskStatus::with_message(TaskState::Working, msg);
        assert_eq!(status.state, TaskState::Working);
        assert!(status.message.is_some());
    }

    // ─── Task tests ──────────────────────────────────────────────────────────────

    #[test]
    fn test_task_creation() {
        let task = Task::new("task-123");
        assert_eq!(task.id, "task-123");
        assert_eq!(task.status.state, TaskState::Submitted);
        assert!(task.history.is_empty());
        assert!(task.artifacts.is_empty());
        assert!(!task.is_terminal());
    }

    #[test]
    fn test_task_transition_valid() {
        let mut task = Task::new("task-456");
        let result = task.transition_to(TaskState::Working);
        assert!(result.is_ok());
        assert_eq!(task.status.state, TaskState::Working);
    }

    #[test]
    fn test_task_transition_invalid() {
        let mut task = Task::new("task-789");
        // submitted → completed is invalid
        let result = task.transition_to(TaskState::Completed);
        assert!(result.is_err());
        // State should not have changed
        assert_eq!(task.status.state, TaskState::Submitted);
    }

    #[test]
    fn test_task_add_artifact() {
        let mut task = Task::new("task-art");
        task.transition_to(TaskState::Working).unwrap();
        task.add_artifact(Artifact::text("report", "Analysis results"));
        assert_eq!(task.artifacts.len(), 1);
    }

    #[test]
    fn test_task_add_message() {
        let mut task = Task::new("task-msg");
        task.add_message(Message::user_text("Start task"));
        assert_eq!(task.history.len(), 1);
    }

    #[test]
    fn test_task_serialization_roundtrip() {
        let mut task = Task::new("task-round");
        task.session_id = Some("session-1".to_string());
        task.status = TaskStatus::with_message(TaskState::Working, Message::agent_text("Processing"));
        task.add_message(Message::user_text("Go"));
        task.add_artifact(Artifact::text("result", "Done"));

        let json = serde_json::to_string_pretty(&task).unwrap();
        let deserialized: Task = serde_json::from_str(&json).unwrap();
        assert_eq!(task, deserialized);
    }

    // ─── Artifact tests ──────────────────────────────────────────────────────────

    #[test]
    fn test_artifact_text() {
        let art = Artifact::text("output", "Result text");
        assert_eq!(art.name, Some("output".to_string()));
        assert_eq!(art.parts.len(), 1);
        assert_eq!(art.index, None);
    }

    #[test]
    fn test_artifact_streaming_chunk() {
        let art = Artifact::streaming_chunk(0, vec![Part::Text { text: "chunk 1".to_string() }], false, false);
        assert_eq!(art.index, Some(0));
        assert_eq!(art.append, Some(false));
        assert_eq!(art.last_chunk, Some(false));
    }

    #[test]
    fn test_artifact_serialization_roundtrip() {
        let art = Artifact::text("report", "The analysis is complete.");
        let json = serde_json::to_string(&art).unwrap();
        let deserialized: Artifact = serde_json::from_str(&json).unwrap();
        assert_eq!(art, deserialized);
    }

    // ─── AgentSkill tests ────────────────────────────────────────────────────────

    #[test]
    fn test_agent_skill_new() {
        let skill = AgentSkill::new("code-review", "Code Review", "Review code for bugs and improvements");
        assert_eq!(skill.id, "code-review");
        assert_eq!(skill.name, "Code Review");
        assert!(!skill.input_modes.is_empty());
        assert!(!skill.output_modes.is_empty());
    }

    #[test]
    fn test_agent_skill_serialization_roundtrip() {
        let skill = AgentSkill {
            id: "search".to_string(),
            name: "Web Search".to_string(),
            description: "Search the web".to_string(),
            tags: vec!["search".to_string(), "web".to_string()],
            examples: vec!["Find documentation on Rust".to_string()],
            input_modes: vec!["text/plain".to_string()],
            output_modes: vec!["text/plain".to_string(), "application/json".to_string()],
        };
        let json = serde_json::to_string(&skill).unwrap();
        let deserialized: AgentSkill = serde_json::from_str(&json).unwrap();
        assert_eq!(skill, deserialized);
    }

    // ─── AgentCard tests ─────────────────────────────────────────────────────────

    #[test]
    fn test_agent_card_new() {
        let card = AgentCard::new("OneAI Agent", "A versatile AI agent", "https://agent.example.com");
        assert_eq!(card.name, "OneAI Agent");
        assert_eq!(card.url, "https://agent.example.com");
        assert!(card.skills.is_empty());
    }

    #[test]
    fn test_agent_card_json_roundtrip() {
        let card = AgentCard {
            name: "TestAgent".to_string(),
            description: "Test description".to_string(),
            url: "https://test.example.com/a2a".to_string(),
            version: Some("1.0.0".to_string()),
            provider: Some(AgentProvider {
                organization: "TestOrg".to_string(),
                url: Some("https://testorg.com".to_string()),
            }),
            skills: vec![AgentSkill::new("skill-1", "Skill One", "First skill")],
            default_input_modes: vec!["text/plain".to_string()],
            default_output_modes: vec!["text/plain".to_string()],
            capabilities: AgentCapabilities {
                streaming: true,
                push_notifications: false,
                state_transition_history: true,
            },
            authentication: AuthenticationInfo {
                schemes: vec!["bearer".to_string()],
                credentials: None,
            },
            documentation_url: Some("https://docs.example.com".to_string()),
        };

        let json = card.to_json_pretty().unwrap();
        let deserialized = AgentCard::from_json(&json).unwrap();
        assert_eq!(card, deserialized);
    }

    #[test]
    fn test_agent_card_from_json() {
        let json = r#"{
            "name": "RemoteAgent",
            "description": "A remote agent for testing",
            "url": "https://remote.example.com",
            "capabilities": {
                "streaming": true,
                "pushNotifications": false,
                "stateTransitionHistory": true
            }
        }"#;
        let card = AgentCard::from_json(json).unwrap();
        assert_eq!(card.name, "RemoteAgent");
        assert!(card.capabilities.streaming);
        assert!(card.capabilities.state_transition_history);
    }

    // ─── PushNotificationConfig tests ────────────────────────────────────────────

    #[test]
    fn test_push_notification_config() {
        let config = PushNotificationConfig {
            url: "https://client.example.com/callback".to_string(),
            authentication: Some(AuthenticationInfo {
                schemes: vec!["bearer".to_string()],
                credentials: None,
            }),
        };
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: PushNotificationConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(config, deserialized);
    }

    // ─── SendTaskParams tests ────────────────────────────────────────────────────

    #[test]
    fn test_send_task_params() {
        let params = SendTaskParams {
            id: "task-new".to_string(),
            message: Message::user_text("Analyze this data"),
            session_id: Some("session-1".to_string()),
            history_length: Some(10),
            push_notification: None,
            metadata: None,
        };
        let json = serde_json::to_string(&params).unwrap();
        let deserialized: SendTaskParams = serde_json::from_str(&json).unwrap();
        assert_eq!(params.id, deserialized.id);
        assert_eq!(params.message, deserialized.message);
    }

    // ─── TaskState serialization ─────────────────────────────────────────────────

    #[test]
    fn test_task_state_kebab_case() {
        // Verify kebab-case serialization per A2A spec
        let state = TaskState::InputRequired;
        let json = serde_json::to_string(&state).unwrap();
        assert_eq!(json, "\"input-required\"");

        let state = TaskState::Working;
        let json = serde_json::to_string(&state).unwrap();
        assert_eq!(json, "\"working\"");

        // Roundtrip
        let deserialized: TaskState = serde_json::from_str("\"input-required\"").unwrap();
        assert_eq!(deserialized, TaskState::InputRequired);
    }
}
