//! OneAI workspace task runner.
//!
//! Generates and verifies the model catalog (`crates/oneai-core/src/catalog/`)
//! from its committed snapshot. Mirrors opencode's build-time catalog generation
//! while respecting OneAI's supply-chain discipline: **no network at build
//! time** — the generated `.rs` + manifest are committed, the crate just
//! declares the static, and `cargo xtask check-model-data` (CI-gated) detects
//! drift between snapshot and generated code.
//!
//! # Subcommands
//!
//! - `gen-model-data`   — snapshot → `models.generated.rs` + `models.manifest.json`.
//! - `check-model-data` — CI gate: re-generate in-memory, byte-compare against the
//!   committed files; exit 1 on drift.
//! - `fetch-model-data` — opt-in maintainer refresh from models.dev (network,
//!   respects `HTTPS_PROXY`). Writes a fresh snapshot for `gen-model-data`.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

const CATALOG_DIR: &str = "crates/oneai-core/src/catalog";
const SNAPSHOT_FILE: &str = "models.snapshot.json";
const GENERATED_FILE: &str = "models.generated.rs";
const MANIFEST_FILE: &str = "models.manifest.json";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().collect();
    let cmd = args.get(1).map(String::as_str).unwrap_or("help");
    match cmd {
        "gen-model-data" => run_gen(),
        "check-model-data" => run_check(),
        "fetch-model-data" => {
            // Network — tokio runtime. Best-effort; on any error print + exit 1.
            match fetch::run_fetch() {
                Ok(()) => ExitCode::SUCCESS,
                Err(e) => {
                    eprintln!("fetch-model-data failed: {e}");
                    ExitCode::FAILURE
                }
            }
        }
        _ => {
            eprintln!("usage: cargo xtask <gen-model-data|check-model-data|fetch-model-data>");
            ExitCode::FAILURE
        }
    }
}

// ─── Paths ───────────────────────────────────────────────────────────────────

/// Resolve the catalog dir relative to the workspace root (CWD may be a
/// subdir). Walks up from CWD until it finds `Cargo.toml` with the workspace.
fn workspace_root() -> PathBuf {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mut dir: &Path = &cwd;
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            if let Ok(contents) = fs::read_to_string(&manifest) {
                if contents.contains("[workspace]") {
                    return dir.to_path_buf();
                }
            }
        }
        dir = match dir.parent() {
            Some(p) => p,
            None => {
                // Fallback: assume CWD is the root.
                return cwd;
            }
        };
    }
}

fn catalog_dir() -> PathBuf {
    workspace_root().join(CATALOG_DIR)
}

// ─── Snapshot model ──────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Serialize)]
struct Snapshot {
    schema_version: u32,
    models: Vec<SnapshotModel>,
}

#[derive(Debug, Deserialize, Serialize)]
struct SnapshotModel {
    provider: String,
    model_id: String,
    context_window: u32,
    max_output_tokens: u32,
    reasoning: bool,
    input_modalities: Vec<String>,
    thinking_format: String,
    supports_strict: bool,
    cache_retention: bool,
    tier: String,
}

// ─── Generation ──────────────────────────────────────────────────────────────

/// Render `models.generated.rs` source text from the snapshot.
fn render_generated(snap: &Snapshot) -> String {
    let mut out = String::new();
    out.push_str(
        "//! **GENERATED by `cargo xtask gen-model-data` — do not edit by hand.**\n\
         //! Source: `models.snapshot.json`. Verified by `cargo xtask check-model-data`.\n\
         \n\
         #![allow(rustdoc::broken_intra_doc_links)]\n\n\
         use crate::catalog::{ModelEntry, ThinkingFormat};\n\
         use crate::model_context::ModelContextEntry;\n\
         use crate::smart_router::RoutingTier;\n\n",
    );

    // CATALOG_JSON: the raw canonical snapshot JSON, embedded for export/HF.
    let canonical = canonical_snapshot_json(snap);
    out.push_str(&format!(
        "/// The canonical snapshot JSON (structure-stable; see `models.manifest.json`).\n\
         pub static CATALOG_JSON: &str = r#\"{canonical}\"#;\n\n",
    ));

    // CATALOG: rich entries.
    out.push_str("/// The generated model catalog — L3 authority.\n");
    out.push_str("pub static CATALOG: &[ModelEntry] = &[\n");
    for m in &snap.models {
        let modalities = m
            .input_modalities
            .iter()
            .map(|s| format!("\"{s}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let tf = match m.thinking_format.to_ascii_lowercase().as_str() {
            "interleaved" => "ThinkingFormat::Interleaved",
            "separate" => "ThinkingFormat::Separate",
            _ => "ThinkingFormat::None",
        };
        let tier = match m.tier.to_ascii_lowercase().as_str() {
            "cheap" => "RoutingTier::Cheap",
            "balanced" => "RoutingTier::Balanced",
            "powerful" => "RoutingTier::Powerful",
            _ => "RoutingTier::Balanced",
        };
        out.push_str(&format!(
            "    ModelEntry {{\n\
             \x20        provider: \"{}\",\n\
             \x20        model_id: \"{}\",\n\
             \x20        context_window: {},\n\
             \x20        max_output_tokens: {},\n\
             \x20        reasoning: {},\n\
             \x20        input_modalities: &[{}],\n\
             \x20        thinking_format: {},\n\
             \x20        supports_strict: {},\n\
             \x20        cache_retention: {},\n\
             \x20        tier: {},\n\
             \x20    }},\n",
            m.provider,
            m.model_id,
            m.context_window,
            m.max_output_tokens,
            m.reasoning,
            modalities,
            tf,
            m.supports_strict,
            m.cache_retention,
            tier,
        ));
    }
    out.push_str("];\n\n");

    // BUILTIN_MODEL_CONTEXT: projection for API compatibility.
    out.push_str(
        "/// Context-window projection — stable L3 record kept for API compatibility.\n\
         /// Generated from `CATALOG` so the two never drift.\n\
         pub static BUILTIN_MODEL_CONTEXT: &[ModelContextEntry] = &[\n",
    );
    for m in &snap.models {
        out.push_str(&format!(
            "    ModelContextEntry {{\n\
             \x20        provider: \"{}\",\n\
             \x20        model_id: \"{}\",\n\
             \x20        context_window: {},\n\
             \x20        max_output_tokens: {},\n\
             \x20    }},\n",
            m.provider, m.model_id, m.context_window, m.max_output_tokens,
        ));
    }
    out.push_str("];\n");

    out
}

/// Canonical (sorted-key) JSON of the snapshot — the structure-hash input.
/// We re-serialize with sorted keys so reordering fields in the snapshot does
/// not change the hash, only adding/removing/revalue-ing entries does
/// (戒律 6: structure hash, not value freeze — but here "structure" includes
/// the model set + their canonical form, which is exactly what we want to
/// detect drift on).
fn canonical_snapshot_json(snap: &Snapshot) -> String {
    let val = serde_json::to_value(snap).expect("snapshot serializes");
    let mut buf = serde_json::to_string_pretty(&canonicalize(val)).expect("canonicalize");
    buf.push('\n');
    buf
}

/// Recursively sort object keys for deterministic JSON.
fn canonicalize(v: serde_json::Value) -> serde_json::Value {
    use serde_json::Value;
    match v {
        Value::Object(map) => {
            let mut items: Vec<(String, Value)> = map.into_iter().collect();
            items.sort_by(|a, b| a.0.cmp(&b.0));
            let mut obj = serde_json::Map::new();
            for (k, v) in items {
                obj.insert(k, canonicalize(v));
            }
            Value::Object(obj)
        }
        Value::Array(arr) => Value::Array(arr.into_iter().map(canonicalize).collect()),
        other => other,
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    let digest = h.finalize();
    let mut s = String::with_capacity(64);
    for b in digest {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

/// Render the manifest: schema_version + structure_hash (over canonical JSON) +
/// per-file SHA256 for the generated file and the snapshot.
fn render_manifest(snap: &Snapshot, generated: &str, snapshot_bytes: &[u8]) -> String {
    let canonical = canonical_snapshot_json(snap);
    let structure_hash = sha256_hex(canonical.as_bytes());
    let gen_hash = sha256_hex(generated.as_bytes());
    let snap_hash = sha256_hex(snapshot_bytes);
    let manifest = serde_json::json!({
        "schema_version": snap.schema_version,
        "structure_hash": structure_hash,
        "files": {
            GENERATED_FILE: gen_hash,
            SNAPSHOT_FILE: snap_hash,
        }
    });
    let mut s = serde_json::to_string_pretty(&manifest).expect("manifest serializes");
    s.push('\n');
    s
}

// ─── Subcommands ─────────────────────────────────────────────────────────────

/// Pipe rendered Rust source through `rustfmt` so the committed generated
/// file is byte-identical to what `cargo fmt` produces — keeping `check-model-data`
/// stable regardless of indentation quirks in the renderer. Falls back to the
/// raw source (with a warning) if rustfmt is unavailable.
fn format_rust(src: &str) -> String {
    use std::io::Write;
    let mut child = match std::process::Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            eprintln!("warning: rustfmt unavailable ({e}); writing unformatted generated code");
            return src.to_string();
        }
    };
    if let Some(mut stdin) = child.stdin.take() {
        let _ = stdin.write_all(src.as_bytes());
    }
    let output = match child.wait_with_output() {
        Ok(o) => o,
        Err(e) => {
            eprintln!("warning: rustfmt failed ({e}); writing unformatted generated code");
            return src.to_string();
        }
    };
    if output.status.success() {
        String::from_utf8_lossy(&output.stdout).into_owned()
    } else {
        eprintln!(
            "warning: rustfmt exited non-zero; writing unformatted generated code: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        src.to_string()
    }
}

fn run_gen() -> ExitCode {
    if let Err(e) = gen_impl() {
        eprintln!("gen-model-data failed: {e}");
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}

fn gen_impl() -> Result<(), String> {
    let dir = catalog_dir();
    let snapshot_path = dir.join(SNAPSHOT_FILE);
    let generated_path = dir.join(GENERATED_FILE);
    let manifest_path = dir.join(MANIFEST_FILE);

    let snapshot_bytes =
        fs::read(&snapshot_path).map_err(|e| format!("read {}: {e}", snapshot_path.display()))?;
    let snap: Snapshot = serde_json::from_slice(&snapshot_bytes)
        .map_err(|e| format!("parse {}: {e}", snapshot_path.display()))?;

    let generated = format_rust(&render_generated(&snap));
    let manifest = render_manifest(&snap, &generated, &snapshot_bytes);

    fs::write(&generated_path, &generated)
        .map_err(|e| format!("write {}: {e}", generated_path.display()))?;
    fs::write(&manifest_path, &manifest)
        .map_err(|e| format!("write {}: {e}", manifest_path.display()))?;

    println!(
        "✓ generated {} ({} models) + {}",
        generated_path.display(),
        snap.models.len(),
        manifest_path.display()
    );
    Ok(())
}

fn run_check() -> ExitCode {
    match check_impl() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("✗ model-data drift: {e}");
            eprintln!("  run `cargo xtask gen-model-data` and commit the result.");
            ExitCode::FAILURE
        }
    }
}

fn check_impl() -> Result<(), String> {
    let dir = catalog_dir();
    let snapshot_path = dir.join(SNAPSHOT_FILE);
    let generated_path = dir.join(GENERATED_FILE);
    let manifest_path = dir.join(MANIFEST_FILE);

    let snapshot_bytes =
        fs::read(&snapshot_path).map_err(|e| format!("read {}: {e}", snapshot_path.display()))?;
    let snap: Snapshot = serde_json::from_slice(&snapshot_bytes)
        .map_err(|e| format!("parse {}: {e}", snapshot_path.display()))?;

    let expected_generated = format_rust(&render_generated(&snap));
    let expected_manifest = render_manifest(&snap, &expected_generated, &snapshot_bytes);

    let actual_generated = fs::read_to_string(&generated_path).map_err(|e| {
        format!(
            "read {}: {e} (run gen-model-data first)",
            generated_path.display()
        )
    })?;
    let actual_manifest = fs::read_to_string(&manifest_path)
        .map_err(|e| format!("read {}: {e}", manifest_path.display()))?;

    if actual_generated != expected_generated {
        return Err(format!(
            "{} does not match snapshot (generated code is stale)",
            GENERATED_FILE
        ));
    }
    if actual_manifest != expected_manifest {
        return Err(format!(
            "{} does not match snapshot (manifest hashes are stale)",
            MANIFEST_FILE
        ));
    }
    println!("✓ model catalog is in sync with snapshot");
    Ok(())
}

// ─── Network fetch (opt-in maintainer) ───────────────────────────────────────

mod fetch {
    use super::*;

    /// Fetch a fresh model catalog from models.dev and write it to the
    /// snapshot path. Maintainer-only; respects `HTTPS_PROXY`/`HTTP_PROXY` via
    /// reqwest's auto-detection. Not run in CI.
    ///
    /// NOTE: models.dev's public schema is community-maintained; this maps the
    /// fields OneAI's catalog consumes. If the upstream schema changes, adjust
    /// the mapping here and re-run `cargo xtask gen-model-data`.
    pub fn run_fetch() -> Result<(), String> {
        let rt = tokio::runtime::Runtime::new().map_err(|e| format!("tokio rt: {e}"))?;
        rt.block_on(async { fetch_impl().await })
    }

    async fn fetch_impl() -> Result<(), String> {
        let dir = catalog_dir();
        let snapshot_path = dir.join(SNAPSHOT_FILE);

        // models.dev exposes per-provider JSON at https://models.dev/{provider}.json
        // and an index at https://models.dev/all.json. We fetch the index and
        // project each model into the snapshot shape. Best-effort: upstream
        // field names may vary; on mismatch the snapshot is left untouched and
        // an error is returned so the maintainer inspects.
        let client = reqwest::Client::builder()
            .user_agent("oneai-xtask")
            .build()
            .map_err(|e| format!("http client: {e}"))?;

        let url = "https://models.dev/all.json";
        let resp = client
            .get(url)
            .send()
            .await
            .map_err(|e| format!("GET {url}: {e}"))?;
        if !resp.status().is_success() {
            return Err(format!("GET {url}: status {}", resp.status()));
        }
        let body: serde_json::Value = resp
            .json()
            .await
            .map_err(|e| format!("decode models.dev JSON: {e}"))?;

        let models = project_models_dev(&body)?;
        let snap = Snapshot {
            schema_version: 1,
            models,
        };
        let json = serde_json::to_string_pretty(&snap).map_err(|e| format!("encode: {e}"))?;
        fs::write(&snapshot_path, format!("{json}\n"))
            .map_err(|e| format!("write {}: {e}", snapshot_path.display()))?;
        println!(
            "✓ fetched {} models from models.dev → {}",
            snap.models.len(),
            snapshot_path.display()
        );
        println!("  run `cargo xtask gen-model-data` to regenerate the Rust + manifest.");
        Ok(())
    }

    /// Project models.dev's `all.json` into the snapshot shape.
    /// models.dev `all.json` is `{ "<provider>": { "models": { "<id>": {...} } } }`.
    fn project_models_dev(body: &serde_json::Value) -> Result<Vec<SnapshotModel>, String> {
        use serde_json::Value;
        let obj = body
            .as_object()
            .ok_or("models.dev all.json is not an object")?;
        let mut out: Vec<SnapshotModel> = Vec::new();
        for (provider, pv) in obj {
            let Some(models) = pv.get("models").and_then(Value::as_object) else {
                continue;
            };
            for (id, mv) in models {
                let model_id = id.clone();
                // models.dev model_id is the full id; OneAI's catalog matches
                // by substring, so keep the short family prefix as the pattern.
                let pattern = short_pattern(provider, &model_id);
                out.push(SnapshotModel {
                    provider: provider.clone(),
                    model_id: pattern,
                    context_window: mv
                        .get("contextWindow")
                        .and_then(Value::as_u64)
                        .unwrap_or(128_000) as u32,
                    max_output_tokens: mv
                        .get("maxOutputTokens")
                        .and_then(Value::as_u64)
                        .unwrap_or(4_096) as u32,
                    reasoning: mv
                        .get("reasoning")
                        .and_then(Value::as_bool)
                        .unwrap_or(false),
                    input_modalities: mv
                        .get("inputModalities")
                        .and_then(Value::as_array)
                        .map(|a| {
                            a.iter()
                                .filter_map(|x| x.as_str().map(String::from))
                                .collect()
                        })
                        .unwrap_or_else(|| vec!["text".to_string()]),
                    thinking_format: mv
                        .get("thinking")
                        .and_then(Value::as_str)
                        .unwrap_or("none")
                        .to_string(),
                    supports_strict: mv
                        .get("supportsJsonSchema")
                        .and_then(Value::as_bool)
                        .unwrap_or(true),
                    cache_retention: mv
                        .get("cacheRetention")
                        .and_then(Value::as_bool)
                        .unwrap_or(false),
                    tier: mv
                        .get("tier")
                        .and_then(Value::as_str)
                        .unwrap_or("balanced")
                        .to_string(),
                });
            }
        }
        if out.is_empty() {
            return Err("models.dev returned no projectable models".into());
        }
        Ok(out)
    }

    /// Heuristically shorten a full model id to the family prefix OneAI's
    /// substring-matcher expects (e.g. `claude-opus-4-20250514` → `claude-opus`).
    fn short_pattern(provider: &str, id: &str) -> String {
        let lower = id.to_lowercase();
        // Take the first two hyphen-separated segments, dropping date/version suffixes.
        let segs: Vec<&str> = lower.split('-').collect();
        if segs.len() >= 2 {
            format!("{}-{}", segs[0], segs[1])
        } else {
            let _ = provider;
            lower
        }
    }
}
